### ISSUE TITLE
Plotting functions return 2 figures

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#5] opened 2019-01-02 12:00 UTC
When plotting with the library sometimes two figures appear. So far I've noticed the issue for:
bw.distribution_by_wind_speed()
bw.SectorRatio.by_sector()
plot, data = bw.monthly_means()
plot, data = bw.TI.by_sector()
plot, data = bw.TI.by_speed()

However, its not happening for:
bw.correl.OrdinaryLeastSquares()

This only happens to some people. Those who have previously used `%matplotlib notebook` in Jupyter notebooks.

**Comment by stephenholleran** [comment] 2019-01-02 12:05
Solved this problem in Jupyter notebooks by turning off inline plotting. This is done by using the command %matplotlib.

Only problem with this approach is it has to be used every time the workbook is opened. Not ideal. Need to find way to turn if off permanently.

Some info at:
https://stackoverflow.com/questions/43027980/purpose-of-matplotlib-inline/43028034

**Comment by Inder95** [comment] 2019-01-13 19:33
This seems like a problem with notebook only. Because the function returns a figure the notebook recognizes it as a plot and also plot whatever is returned. A way to get around this problem is to return the axes instead of figure as it is done in pandas (https://github.com/pandas-dev/pandas/issues/3474).

I am looking into how this will change the user interface to plotting (or it might not change).

**Comment by stephenholleran** [comment] 2019-01-15 12:31
It seems that something was turned on in Jupyter Notebooks at some point for these people. Therefore it must be able to be turned off?

**Comment by Inder95** [comment] 2019-01-15 17:43
Typing the following in notebook to turn inline plotting off also works:
```
%matplotlib
```

**Comment by Inder95** [comment] 2019-01-17 11:56
@stephenholleran  I stumbled across a different method to solve this. As of now we are returning axes from the library and not the figure. Axes allow user to more easily make changes to the plot. If we return figure instead, this problem goes away. But it is a little for difficult for the user to modify plots then, he has to get the axes from the figure
```python 
ax = fig.get_axes()
#make changes to axes
fig
```
Stephen, I think it is a better way to go forward. User is still able to change it and nothing extra in the notebook. let me know what do you think.

**Comment by stephenholleran** [comment] 2019-01-17 12:01
How would this code change for the user:
`bw.monthly_mean(data)`
In a notebook it plots the monthly mean wind speeds straight away. Will what you are suggesting do the same?

**Comment by Inder95** [comment] 2019-01-17 17:11
Sorry, this does not solve the problem. It was something else where it works not with the functions outlined in this issue.

**Comment by stephenholleran** [comment] 2019-06-14 12:42
@lucunnin These two links might shed some light onto this:

https://github.com/statsmodels/statsmodels/issues/1265

https://stackoverflow.com/questions/36685031/why-is-jupyter-notebook-creating-duplicate-plots-when-making-updating-plots

Search Google for other solutions too.

**Comment by Inder95** [comment] 2019-06-14 14:43
> @lucunnin These two links might shed some light onto this:
> 
> [statsmodels/statsmodels#1265](https://github.com/statsmodels/statsmodels/issues/1265)
> 
> https://stackoverflow.com/questions/36685031/why-is-jupyter-notebook-creating-duplicate-plots-when-making-updating-plots
> 
> Search Google for other solutions too.

I did try that semi-colon solution in the past and didn't work (my thumbs-down is still there on that comment ;) ), you can skip that. Most other solutions are based on things we can do in notebooks.

**Comment by lucunnin** [comment] 2019-06-14 14:56
@stephenholleran 
Other resources for this problem:

https://github.com/facebook/prophet/issues/344

https://groups.google.com/forum/#!topic/pystatsmodels/OIcl1B4X7MY

https://stackoverflow.com/questions/35422988/matplotlib-user-defined-plot-function-print-twice

The most reasonable solution which seems to fit the library's needs, i.e. doesnt stop a plot or data being returned by the function is to insert a plt.close() before the return statement in each of the plot functions. This simply closes the plot created by python, while the plot created by the notebook is displayed to the user. The plot is still however be returned and available to be called/used later.

**Comment by lucunnin** [comment] 2019-06-14 15:00
@Inder95 

I have seen them! The semi colon option does work for me, but I dont think it would be very user-friendly. Try the plt.close() option as I described above, I think it could work.

**Comment by Inder95** [comment] 2019-06-14 15:11
> @Inder95
> 
> I have seen them! The semi colon option does work for me, but I dont think it would be very user-friendly. Try the plt.close() option as I described above, I think it could work. It is mentioned in one of the links you sent.

I meant using semi-colons in the library itself instead of notebooks. And that is for all other solutions too, we are trying to make changes in the library rather than notebook. In notebook you can get away with most of these by assigning a variable to the output.

**Comment by lucunnin** [comment] 2019-06-14 15:13
> I meant using semi-colons in the library itself instead of notebooks. And that is for all other solutions too, we are trying to make changes in the library rather than notebook. In notebook you can get away with most of these by assigning a variable to the output.

Ah yes, that doesnt work for me either. The plt.close() solution an be implemented within the library code itself and requires no additional action from the user.

**Comment by lucunnin** [comment] 2019-06-14 15:22
@Inder95 

Stephen and I have discussed it and think we will go with the plt.close() as we cannot foresee any issues arising from it. Can you think of any issues that this could cause?

**Comment by Inder95** [comment] 2019-06-14 15:40
> @Inder95
> 
> Stephen and I have discussed it and think we will go with the plt.close() as we cannot foresee any issues arising from it. Can you think of any issues that this could cause?

When using library from command line and not from notebooks you will never see a plot. I haven't checked it though, but this what I guess.

**Comment by lucunnin** [comment] 2019-06-14 15:46
> > @Inder95
> > Stephen and I have discussed it and think we will go with the plt.close() as we cannot foresee any issues arising from it. Can you think of any issues that this could cause?
> 
> When using library from command line and not from notebooks you will never see a plot. I haven't checked it though, but this what I guess.
> 
> Also sometimes you use notebooks in an interactive (%pylab) mode where a new window is opened where you can zoom-in/out of the graph and scroll around too. That too might not work.

Yeah, I agree. Good points. I tried interactive mode there and it does not work. I will look into some other solutions.

**Comment by stephenholleran** [comment] 2019-06-14 16:26
Would running plt.show() not bring up the plot again when using the command line?

**Comment by lucunnin** [comment] 2019-06-17 12:36
@Inder95 @stephenholleran 

> When using library from command line and not from notebooks you will never see a plot. I haven't checked it though, but this what I guess.
> Also sometimes you use notebooks in an interactive (%pylab) mode where a new window is opened where you can zoom-in/out of the graph and scroll around too. That too might not work.

I can confirm that running plt.show() in the command line will still display the plot. 

With regards to interactive plotting, the plots seem to work fine. The only minor issue is that when a function is called, i.e :

plot = monthly_means(data)

a blank space will appear in the notebook where the plot would be, as it it obvioously being opened and closed very quickly. The plot can be viewed interactively then by just returned the object 'plot'.

**Comment by lucunnin** [comment] 2019-06-17 12:59
@stephenholleran @Inder95 

I can confirm that running plt.show() will display the plot.

With regards to the interactive plotting, it is still possible with the plt.close() solution. The one issue is that when using interactive plotting, a  blank space will appear in the notebook where the extra plot has appeared and is closed by plt.close(). You do not see the plot opening and closing, but the blank space may be confusing to users.

**Closed** 2019-06-18 15:24 UTC
Labels: question
