### ISSUE TITLE
[monthly_means] y-axis label not showing up in plot

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#416] opened 2023-10-06 17:20 UTC
**Describe the bug**
When using the `monthly_means()` function the y-axis label does not show. 

![image](https://github.com/brightwind-dev/brightwind/assets/25622575/39ea36c8-245b-4126-a579-0efd64a4b797)

**Comment by BiancaMorandi** [comment] 2023-10-10 08:14
@stephenholleran the issue you have generated here is a duplicate of what I have already created #413. I am going to close this.

**Closed by BiancaMorandi** 2023-10-10 08:14 UTC
Labels: bug
